src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions</description>
    <fields>
        <fullName>Birthday__c</fullName>
        <label>Birthday</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua &amp; Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei Darussalam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burkina Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Myanmar/Burma</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Employer__c</fullName>
        <label>Current Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currently_Employed__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To check candidate is still working for current company or free</description>
        <label>Currently Employed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <picklist>
            <picklistValues>
                <fullName>HS Diploma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA/BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA/MS/MBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ph.D.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Doc</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <externalId>true</externalId>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Years_of_Experience__c</fullName>
        <label>Years of Experience</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MR_CandidateRegister.cls
public with sharing class MR_CandidateRegister {
    // procedure constructor
	public MR_CandidateRegister(ApexPages.StandardController controller) {

	}
    
   @RemoteAction
    public static String toRegister ( String  firstName,
                                      String  lastName,
                                      String  birthday,
                                      String  phone,
                                      String  email,
                                      String  street,
                                      String  city,
                                      String  stateProvince,
                                      String  zipPostalCode,
                                      String  country,
                                      String  currentCompany,
                                      Boolean currentlyEmployed,
                                      Integer yearsOfExperience,
                                      String  education
                                    ) {
                                          
        Candidate__c candidate               = new Candidate__c();
        candidate.First_Name__c              = firstName;
        candidate.Last_Name__c               = lastName;
        //check and initialization date
        if( !String.isBlank(birthday) ) {
            Date newDate                     = Date.valueOf(birthday);
            candidate.Birthday__c            = newDate;
        }
        candidate.Phone__c                   = phone;
        candidate.Email__c                   = email;
        candidate.Street__c                  = street;
        candidate.City__c                    = city;
        candidate.State_Province__c          = stateProvince;
        candidate.Zip_Postal_Code__c         = zipPostalCode;
        candidate.Country__c                 = country;
        candidate.Current_Employer__c        = currentCompany;
        candidate.Currently_Employed__c      = currentlyEmployed;
        if(yearsOfExperience == null) {
            candidate.Years_of_Experience__c = 0;
        } else {
            candidate.Years_of_Experience__c = yearsOfExperience;
        }
        
        candidate.Education__c               = education;

        try {
            insert candidate;
        } catch ( DmlException ex ) {
            return ex.getMessage();
        }

        return candidate.Id;
    }

    @RemoteAction
	public static String getJSONCandidates() {
		// serialize to JSON
		return JSON.serialize([SELECT First_Name__c, Last_Name__c FROM Candidate__c]);
	}

    @RemoteAction
	public static String getCountryPickList() {
		Schema.DescribeFieldResult fieldCountry = Candidate__c.Country__c.getDescribe();
		List<Schema.PicklistEntry> pickListCountry = fieldCountry.getPicklistValues();
		return JSON.serialize(pickListCountry);
    }
    
    @RemoteAction
	public static String getEducationPickList() {
		Schema.DescribeFieldResult fieldEducation = Candidate__c.Education__c.getDescribe();
		List<Schema.PicklistEntry> pickListEducation = fieldEducation.getPicklistValues();
		return JSON.serialize(pickListEducation);
	}
}