src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions</description>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MR_EmailManager.cls
public class MR_EmailManager {
    public static void sendConfirmEmails(List<Candidate__c> lstCandidates) {
        List<Messaging.SingleEmailMessage> listMail = new List<Messaging.SingleEmailMessage>();
        //Select EmailTemplate send mail
        EmailTemplate templateId = [SELECT Id FROM EmailTemplate WHERE Name = 'Email' LIMIT 1];
        
        for (Candidate__c candidate: lstCandidates) {
            Messaging.SingleEmailMessage email =  Messaging.renderStoredEmailTemplate(templateId.Id, candidate.OwnerID, candidate.Id);
            String[] toAddresses = new String[] {candidate.Email__c};
            email.setToAddresses(toAddresses);
            email.setSaveAsActivity(false);
            listMail.add(email);
        }
        //Call method send email
        Messaging.sendEmail(listMail);
    }
}