src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MR_CandidateWeatherControllerTest.cls
@isTest
private class MR_CandidateWeatherControllerTest {
	@isTest static void weatherMethod() {

		// set mock callout class
        Test.setMock( HttpCalloutMock.class, new MR_WeatherMock() );

        // create & insert a new Candidate to get Id & City(Location)
		Candidate__c can = new Candidate__c( City__c = 'Sai Gon' );

		insert can;

		// Put Id to page
		ApexPages.currentPage().getParameters().put( 'id', can.Id );

		// Define new instance for testing
		MR_CandidateWeatherController cwbl = new MR_CandidateWeatherController();

		MR_CandidateWeatherController.WeatherInfoDao wid = cwbl.weatherInfo;

		System.assertEquals( 5, wid.Coord.lon );
		System.assertEquals( 15, wid.Coord.lat );
		System.assertEquals( 'Sai Gon', can.City__c );
	}
}