src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions</description>
    <fields>
        <fullName>Birthday__c</fullName>
        <label>Birthday</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua &amp; Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei Darussalam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burkina Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Myanmar/Burma</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Employer__c</fullName>
        <label>Current Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currently_Employed__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To check candidate is still working for current company or free</description>
        <label>Currently Employed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <picklist>
            <picklistValues>
                <fullName>HS Diploma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA/BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA/MS/MBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ph.D.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Doc</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <externalId>true</externalId>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Years_of_Experience__c</fullName>
        <label>Years of Experience</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MR_CandidateRegisterTest.cls
@isTest
private class MR_CandidateRegisterTest {
    @isTest static void testCandidateRegister01() {
        String  firstName          = 'Tran Hung';
        String  lastName           = 'Binh';
        String  email              = 'tran.binh@mulodo.com';
        String  phone              = '0123456789';
        String  birthday      	   = '1989-01-01 00:00:00';
        String  street             = 'Ly Chinh Thang';
        String  city               = 'HCM';
        String  stateProvince      = '3';
        String  zipPostalCode      = '13';
        String  country            = 'Albania';
        String  currentCompany     = 'Mulodo';
        Integer yearsOfExperience  = 3;
        Boolean currentlyEmployed  = true;
        String  education          = 'HS Diploma';
        // Implement test code
        Id id                      = MR_CandidateRegister.toRegister(firstName, lastName, birthday, phone, email, street, city, stateProvince, zipPostalCode,
                                                              country, currentCompany, currentlyEmployed, yearsOfExperience, education);
        Candidate__c listCandidate = [SELECT First_Name__c, Last_Name__c, Birthday__c, Phone__c, Email__c, Street__c, City__c, State_Province__c,
                                            Zip_Postal_Code__c, Country__c, Current_Employer__c, Currently_Employed__c, Years_of_Experience__c, Education__c
                                            FROM Candidate__c WHERE Candidate__c.Id =: id];
        System.assertEquals('Tran Hung', listCandidate.First_Name__c);
        System.assertEquals('Binh', listCandidate.Last_Name__c);
        System.assertEquals(Date.parse('01/01/1989'), listCandidate.Birthday__c);
        System.assertEquals('0123456789', listCandidate.Phone__c);
        System.assertEquals('tran.binh@mulodo.com', listCandidate.Email__c);
        System.assertEquals('Ly Chinh Thang', listCandidate.Street__c);
        System.assertEquals('HCM', listCandidate.City__c);
        System.assertEquals('3', listCandidate.State_Province__c);
        System.assertEquals('13', listCandidate.Zip_Postal_Code__c);
        System.assertEquals('Albania', listCandidate.Country__c);
        System.assertEquals('Mulodo', listCandidate.Current_Employer__c);
        System.assertEquals(true, listCandidate.Currently_Employed__c);
        System.assertEquals(3, listCandidate.Years_of_Experience__c);
        System.assertEquals('HS Diploma', listCandidate.Education__c);
    }
    
     @isTest static void testCandidateRegister02() {
        String  firstName          = 'Tran Hung';
        String  lastName           = 'Binh';
        String  email              = 'tran.binh@gmail.com';
        String  phone              = '0123456789';
        String  birthday      	   = '1989-01-01 00:00:00';
        String  street             = 'Ly Chinh Thang';
        String  city               = 'HCM';
        String  stateProvince      = '3';
        String  zipPostalCode      = '13';
        String  country            = 'Albania';
        String  currentCompany     = 'Mulodo';
        Integer yearsOfExperience  = 3;
        Boolean currentlyEmployed  = true;
        String  education          = 'HS Diploma';
        // Implement test code
        String result              = MR_CandidateRegister.toRegister(firstName, lastName, birthday, phone, email, street, city, stateProvince, zipPostalCode,
                                                              country, currentCompany, currentlyEmployed, yearsOfExperience, education);
        System.assertEquals('Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Invalid email format: []', result);
    }
    
    @isTest static void testCandidateRegister03() {
        String  firstName          = 'Tran Hung';
        String  lastName           = 'Binh';
        String  email              = 'tran.binh@mulodo.com';
        String  phone              = '01234';
        String  birthday      	   = '1989-01-01 00:00:00';
        String  street             = 'Ly Chinh Thang';
        String  city               = 'HCM';
        String  stateProvince      = '3';
        String  zipPostalCode      = '13';
        String  country            = 'Albania';
        String  currentCompany     = 'Mulodo';
        Integer yearsOfExperience  = 3;
        Boolean currentlyEmployed  = true;
        String  education          = 'HS Diploma';
        // Implement test code
        String result              = MR_CandidateRegister.toRegister(firstName, lastName, birthday, phone, email, street, city, stateProvince, zipPostalCode,
                                                              country, currentCompany, currentlyEmployed, yearsOfExperience, education);
        System.assertEquals('Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Incorrect phone number format: []', result);
    }
    
    @isTest static void testCandidateRegister04() {
        String  firstName          = '';
        String  lastName           = 'Binh';
        String  email              = 'tran.binh@mulodo.com';
        String  phone              = '01234564789';
        String  birthday      	   = '1989-01-01 00:00:00';
        String  street             = 'Ly Chinh Thang';
        String  city               = 'HCM';
        String  stateProvince      = '3';
        String  zipPostalCode      = '13';
        String  country            = 'Albania';
        String  currentCompany     = 'Mulodo';
        Integer yearsOfExperience  = 3;
        Boolean currentlyEmployed  = true;
        String  education          = 'HS Diploma';
        // Implement test code
        String result              = MR_CandidateRegister.toRegister(firstName, lastName, birthday, phone, email, street, city, stateProvince, zipPostalCode,
                                                              country, currentCompany, currentlyEmployed, yearsOfExperience, education);
          System.assertEquals('Insert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [First_Name__c]: [First_Name__c]', result);
    }

    @isTest static void testCandidateRegister05() {
        String  firstName          = 'Tran';
        String  lastName           = '';
        String  email              = 'tran.binh@mulodo.com';
        String  phone              = '01234564789';
        String  birthday      	   = '1989-01-01 00:00:00';
        String  street             = 'Ly Chinh Thang';
        String  city               = 'HCM';
        String  stateProvince      = '3';
        String  zipPostalCode      = '13';
        String  country            = 'Albania';
        String  currentCompany     = 'Mulodo';
        Integer yearsOfExperience  = 3;
        Boolean currentlyEmployed  = true;
        String  education          = 'HS Diploma';
        // Implement test code
        String result              = MR_CandidateRegister.toRegister(firstName, lastName, birthday, phone, email, street, city, stateProvince, zipPostalCode,
                                                              country, currentCompany, currentlyEmployed, yearsOfExperience, education);
        System.assertEquals('Insert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [Last_Name__c]: [Last_Name__c]', result);
    }  
    
      @isTest static void testCandidateRegister06() {
        String  firstName          = 'Tran';
        String  lastName           = 'Binh';
        String  email              = 'tran.binh@mulodo.com';
        String  phone              = '01234564789';
        String  birthday      	   = '2017-01-01 00:00:00';
        String  street             = 'Ly Chinh Thang';
        String  city               = 'HCM';
        String  stateProvince      = '3';
        String  zipPostalCode      = '13';
        String  country            = 'Albania';
        String  currentCompany     = 'Mulodo';
        Integer yearsOfExperience  = 3;
        Boolean currentlyEmployed  = true;
        String  education          = 'HS Diploma';
        // Implement test code
        String result              = MR_CandidateRegister.toRegister(firstName, lastName, birthday, phone, email, street, city, stateProvince, zipPostalCode,
                                                              country, currentCompany, currentlyEmployed, yearsOfExperience, education);
        System.assertEquals('Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Birthday less than 16 years old: []', result);
    }  
    
    @isTest static void testGetEducationPickList() {
		Test.startTest();
		String educationPickList = MR_CandidateRegister.getEducationPickList();
		Test.stopTest();
		System.assert(educationPickList != null, 'Should be able to get Education Pick List');
	}
    
    @isTest static void testGetCountryPickList() {
        Test.startTest();
        String countryPickList = MR_CandidateRegister.getCountryPickList();
        Test.stopTest();
        System.debug(countryPickList);
        System.assert(countryPickList != null, 'Should be able to get Country Pick List');
	}
}