src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions</description>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmailManager.cls
public class EmailManager {

    public static void sendConfirmEmails(List<Candidate__c> lstCandidates) {
    	List<Messaging.SingleEmailMessage> listMail = new List<Messaging.SingleEmailMessage>();
    	EmailTemplate templateId = [SELECT Id FROM EmailTemplate WHERE Name = 'Candidate Confirm' LIMIT 1];
  
    	for (Candidate__c candidate: lstCandidates) {
    		Messaging.SingleEmailMessage mail =  Messaging.renderStoredEmailTemplate(templateId.Id, candidate.OwnerID, candidate.Id);
			String[] toAddresses = new String[] {candidate.Email__c};
	        mail.setToAddresses(toAddresses);
			mail.setSaveAsActivity(false);
	       	listMail.add(mail);
    	}
		Messaging.SendEmailResult [] result= Messaging.sendEmail(listMail);
		System.debug(result);
    }
}